name: Gestionar Deudas Técnicas

on:
  push:
    branches:
      - main
      - master

jobs:
  analizar-deuda:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install PyGithub

      - name: Ejecutar analizador de deuda técnica
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python manage_deuda.py
